services:
    nginx:
        container_name: nginx
        build:          ./requirements/nginx/
        image:          nginx-img-inception
        env_file:       .env
        networks:
            - inception
        ports:
            - "443:443"
        restart:        on-failure
        volumes:
            - wordpress-data:/var/www/html/
        depends_on:
            - wordpress
    mariadb:
        container_name: mariadb
        build:          ./requirements/mariadb/
        image:          mariadb-img-inception
        env_file:       .env
        networks:
            - inception
        secrets:
            - db_root_pass
            - db_host
            - wp_db_user
            - wp_db_pass
        restart:        on-failure
        volumes:
            - mariadb-data:/var/lib/mysql/
    wordpress:
        container_name: wordpress
        build:          ./requirements/wordpress/
        image:          wordpress-img-inception
        env_file:       .env
        networks:
            - inception
        secrets:
            - db_root_pass
            - db_host
            - wp_db_user
            - wp_db_pass
            - wp_admin_pass
            - wp_admin_user
            - wp_user_pass
            - wp_user
        restart:        on-failure
        volumes:
            - wordpress-data:/var/www/html/
        depends_on:
            - mariadb
    redis:
        container_name: redis
        image:          redis-img-inception
        init: true
        build:          ./requirements/bonus/redis
        volumes:
            - wordpress-data:/var/www/html/
        networks:
            - inception
        restart:        on-failure
        depends_on:
            - wordpress
    ftp-server:
        container_name: ftp-server
        image:          ftp-server-img-inception
        env_file:       .env
        build:          requirements/bonus/ftpserver
        init: true
        ports:
            - "21:21"
            - "21100-21110:21100-21110"
        volumes:
            - wordpress-data:/var/www/html/
        networks:
            - inception
        secrets:
            - ftp_user
            - ftp_pass
        restart:        on-failure
    adminer:
        container_name: adminer
        image:          adminer-img-inception
        env_file:       .env
        build:          requirements/bonus/adminer
        expose:
            - "9000"
        networks:
            - inception
        restart:        on-failure
        depends_on:
            - mariadb
    webserv:
        container_name: webserv
        image:          webserv_img-inception
        build:          requirements/bonus/webserv
        init:        true
        ports:
            - "8084:8084"
            - "8086:8086"
        env_file:       .env
        networks:
            static_site:
                ipv4_address: 192.168.1.101
        volumes:
            - webserv-data:/webserv/www/
        restart:        on-failure
    cadvisor:
        container_name: cadvisor
        image: cadvisor_img-inception
        build: requirements/bonus/cadvisor
        networks:
            - inception
        ports:
            - "8080:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        restart:        on-failure
networks:
    inception:
        name:   inception
        driver: bridge
    static_site:
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_PATH}/mariadb-data
  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_PATH}/wordpress-data
  webserv-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_PATH}/webserv-data

secrets:
    db_root_pass:
        file: ../secrets/db_root_pass.txt
    db_host:
        file: ../secrets/db_host.txt
    wp_db_user:
        file: ../secrets/wp_db_user.txt
    wp_db_pass:
        file: ../secrets/wp_db_pass.txt
    wp_admin_pass:
        file: ../secrets/wp_admin_pass.txt
    wp_admin_user:
        file: ../secrets/wp_admin_user.txt
    wp_user_pass:
        file: ../secrets/wp_user_pass.txt
    wp_user:
        file: ../secrets/wp_user.txt
    ftp_user:
        file: ../secrets/ftp_user.txt
    ftp_pass:
        file: ../secrets/ftp_pass.txt
    
